    version: '3.7' # версия доккера
    services: # Список сервисов которые мы будем заупскать
      web: # один из сервисов, название не важно
        build: # блок который описывает процесс сборки контейнера
          context: '' # команда которая указывает на список файлов для сборки
          dockerfile: Dockerfile # файл который отвечает за сборку
        ports: # список мостов между портами компьютера и докер контейнера
          - "8000:80000" # мост 8000 порта
        command: # блок отвечающий за команды выполняющиеся после сборки контейнера
          python manage.py runserver 0.0.0.0:8000 # запуск джанго проекта