# Generated by Django 4.0.4 on 2022-04-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
