# Generated by Django 4.0.4 on 2022-04-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_model_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=255)),
                ('lastname', models.CharField(default=None, max_length=255)),
                ('age', models.IntegerField()),
                ('text', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
