# Generated by Django 4.0.3 on 2022-04-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_customer_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.profession'),
        ),
    ]
