# Generated by Django 4.0.3 on 2022-04-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='main_app.contactinfo'),
        ),
    ]
