# Generated by Django 4.0.3 on 2022-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_hobbies_customer_hobbies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobbies',
            options={'verbose_name': 'Hobby', 'verbose_name_plural': 'Hobby'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='hobbies',
            field=models.ManyToManyField(related_name='customers', to='main_app.hobbies'),
        ),
    ]
